; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Blue Moon v1.21"
#define MyAppVersion "1.21"
#define MyAppPublisher "Blue Moon Trading Company, Lda"
#define MyAppURL "https://www.facebook.com/profile.php?id=61555739220539&mibextid=ZbWKwL"
#define MyAppExeName "Blue Moon.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0A6EAB8B-FD48-4DDC-AE2F-DA54634C39A5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\MyProgRAM\Blue Moon
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\LICENSE.txt
InfoBeforeFile=C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\before.txt
InfoAfterFile=C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\after.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\Ramadan ismaeL\Desktop
OutputBaseFilename=Setup Blue Moon v1.21
SetupIconFile=C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\icone.ico
Password=ramadanBlueMoon5126
Encryption=yes
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\MySQL\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\after.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\Blue Moon.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\build.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\cap2.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\config.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\icone.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\manifest.mf"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\my.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Ramadan ismaeL\Desktop\MyProgRAM\Proj_BlueMoon.jar"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\my.bat"; Flags: nowait postinstall skipifsilent
